{% set name = "geolinks" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geolinks-{{ version }}.tar.gz
  sha256: 1aacd55d0c0c349cbc8319b2eea70e98dbe34be688c7be14248fbbba0c7cf54e

build:
  entry_points:
    - geolinks=geolinks:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - click

test:
  imports:
    - geolinks
  commands:
    - pip check
    - geolinks --help
  requires:
    - pip

about:
  home: https://github.com/geopython/geolinks
  summary: Utilities to deal with geospatial links
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
