{% set version = "0.2.1" %}

package:
  name: geolinks
  version: {{ version }}

source:
  fn: geolinks-{{ version }}.tar.gz
  url: https://github.com/geopython/geolinks/archive/{{ version }}.tar.gz
  sha256: fb7a6b517a3cf4701ca5bc81a9d39c9c2644b3e532e6d0e4059ad82e4f756c70

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - geolinks

about:
  home: https://github.com/geopython/geolinks
  license: MIT
  license_file: LICENSE
  summary: Utilities to deal with geospatial links.

extra:
  recipe-maintainers:
    - ocefpaf
