travis:
  secure:
    BINSTAR_TOKEN: bilO7mYkKZq+m2vfxWSFsd+tiMhaBQO71V+fPH8CIUihLuo0mfdCfdyo3QnEfd0FZG/vf5UoheMcINKTrgc8wfHK4oJU5p4RWRY0UTc+ny+RypNMFzPKEI6haFbonbaZHpVzmQLJwRUNyPXPIk1A3jhzVUSKqHqadvt9vwq3xzxMAOMMRdRlccOafiAITXhL1WMVMAQo7Ih6DDFMmwl6jQCA1k2Qz3G1Qt3piG9HODcJ0UwwXr43N8MI5GQIdQSLtATXdOxfL1c/3eORAAiEHZI7JaJReI+kunP3W0g0D61Tgp/otUpw1M4al05uo5Hx0dw1JixWkuscQDaKsx6R3UyKhhtWtSAo3SkjKlNOwmrrcCb434lID/wvgWxN/nmQomUGFZH2gOgYd/xxmfk6jJOqzHfwvii4rIdtFwKLtwqhc/5NMGUBweEleQuEtjz1ksLfYPVTgti2J8BA2uyOzDE5ugbzLjr53HC4E82X03PO8vJEPPuLNvt8oyORE5jCb9/7By9ThW5V0mi99DqQKDnBKAYN1NccoIcDMcq1u9WrgzvU8RdFHKaQMPo1XkzmSiHb4iVaJ3vkCGoJyad6zGlC9AoRrtRwpsy/PSeaULN5MUvfE0zW7Hi6ktiQvBVDBVRWZBqpYvKWAIGGPcC+qWeFpjv3xMZhd+y42s7qm1w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
