travis:
  secure:
    BINSTAR_TOKEN: Lp4ujPerzqMCE8TyPt/vBOd8CGdwkcRld2uU39wyFMOSMujFEv6wp9WJRaqnHce/TAHVCetoqLGm0WzGkyTAfuPGzlQenoXmD7KRbamtRwKdX2ba5Sk4HE2vFOGqmRTh5zc8c/kpXCo2tuJvPEp0PY5CDvNF0CXzXzWWw4X3syBrX0iOMWWJEQMIuADNg+XNEtHmIQSjoW9R9r38of9B/xPfniJYGSkghPq9w711m8slsLkPyNgFVgINLBMsZ6xe39CRLBB6g0OPUPTqSCDpbKmhwZpQG0C3drWyqI89TQAy56oni34GJIi3hgHy2MkX8BGObM3yFZHLz2OHa7am9CYvpLTW9wqMGzqAMiRZVhCTr2n2Y8jMA5mGCqMMZIVoYkN+ql2Bp3sOGlz4tWrVH8rOXMUiUhXyk6GsVnEDV2znWtBvFTcWEX14zvDtpXCq5F1HTqBL4NWyqwgCoa/aa4JnRtc9mg+jkyZCnBDBDXeeKuQvRPpboVoaWDrPleWrgfVymzY7nhRqcf/xsA0pespV5Ad91j5zrobGADDZjDgjxL1YekVTOw0yVLFJtbj99ZmFfAS1WpPLF9fix3HDfijKmkoFlLSOSXQ/juQn6KwqHkpNu4JA/OrkFUGToE+QHV8sHKhr/Ufid3hafZj5q3SCxf2h7lV0IEhj23+hLIg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
